### PR TITLE
Fix pagination continueCursor at end of query

### LINKED ISSUE #16: Wrong types for `PaginationResult`
From [Discord](https://discord.com/channels/1019350475847499849/1271519463400931389)

continueCursor should be `string | null`, now it's just `string`

```ts
import type { PaginationResult } from 'convex/server'
import { describe, expect, it } from 'vitest'
import { convexTester } from '~/convex/utils/setup.testing'
import { api } from '../_generated/api'
import type { Doc, Id } from '../_generated/dataModel'

describe.concurrent.only('posts', () => {
  it('should return empty collection on no data', async () => {
    const t = convexTester()
    expect(
      await t.query(api.user.posts.default, {
        userId: '1;users' as Id<'users'>,
        cursor: null,
      }),
    ).toEqual({
      // @ts-expect-error the tests passes, therefore, the value is null
      continueCursor: null,
      isDone: true,
      page: [],
    } satisfies PaginationResult<Doc<'posts'>>)
  })
})
```

Maybe it's just testing behavior. If it is, then there's a bug in convex-test.

### PR DESCRIPTION
**Pull request by ldanilek**
Fixes #16 and #17 

----

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: index.ts [hunk 1]
```diff
@@ -371,6 +371,9 @@ class DatabaseFake {
       const { value, done } = this.queryNext(queryId);
       if (done) {
         isDone = true;
+        // We have reached the end of the query. Return a cursor that indicates
+        // "end query", which we can do with any string that isn't a valid _id.
```
Comment (ianmacartney) [inline index.ts:375]: this is magical but I'll take it

File: index.ts [hunk 2]
```diff
@@ -387,7 +390,7 @@ class DatabaseFake {
     return {
       page,
       isDone,
-      continueCursor,
+      continueCursor: continueCursor!,
```
Comment (ianmacartney) [inline index.ts:393]: Is it possible there won't be any result & it'll still be null?

**Review by ianmacartney — APPROVED** [review]

File: index.ts (hunk 2 above)
Comment (ldanilek) [reply index.ts:393]: nope it's an infinite loop with two breaks and we set the variable before each break
